# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1nCV882f0h0KFlU5HRGi48ZZFd9Z8wMrv
"""

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newarr = arr.reshape(2,5,2)
print(newarr)