# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1s2L9S58q3lvO737Grq8MQtCHHluN4Ez1
"""

from numpy import random
x = random.randint(100,size=(5,10))

import numpy as np
arr=np.array(x)
print(np.sort(arr))